version: '{build}'

environment:
  LOG_TRACE: 1

install:
  - nuget install -ConfigFile Stuff\NuGet.config -OutputDirectory Stuff -ExcludeVersion Stuff\packages.config
  - ps: Invoke-WebRequest https://files.fusetools.com/tooling/iyVp8kwQ0vLn-mesa-17.2.3.500.zip -OutFile mesa.zip
  - ps: Expand-Archive mesa.zip mesa

build_script:
  - bash pack.sh
  - 7z a fuselibs-artifacts-%APPVEYOR_BUILD_NUMBER%.zip upload\*.*

artifacts:
  - path: fuselibs-artifacts-%APPVEYOR_BUILD_NUMBER%.zip

before_test:
  - ps: |
      Get-ChildItem -Path Source -Recurse -Include *Test.unoproj | Select-Object -ExpandProperty DirectoryName | Foreach-Object {
        $buildDir = Join-Path $_ build\Test\DotNet
        New-Item -Force -ItemType directory -Path $buildDir | Out-Null
        Copy-Item -Path mesa\x64\opengl32.dll -Destination (Join-Path $buildDir opengl32.dll)
      }

test_script:
  - Stuff\uno test -tDotNet Source
