os: osx
osx_image: xcode9.2
language: csharp
mono: 5.4.1

env:
  global:
    - XCODE_XCCONFIG_FILE=$TRAVIS_BUILD_DIR/.travis.xcconfig

install:
  - sudo easy_install pip
  - pip install six
  - nuget install -ConfigFile Stuff/NuGet.config -OutputDirectory Stuff -ExcludeVersion Stuff/packages.config

before_script:
  - ulimit -c unlimited -S
  - rm -rf /cores/core.*

script:
  - Stuff/uno --trace doctor
  - Stuff/uno --trace build -tios Tests/ManualTests/ManualTestingApp/ManualTestingApp.unoproj
  - Stuff/uno --trace test -tnative --timeout=30 Source/AllTests.unoproj

after_failure:
  - for c in $(ls /cores/core.*); do
      lldb -c $c -o "bt all" -b;
    done
